config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'lifestyle', to:'pages#lifestyle'

  get 'videos', to:'pages#videos'

  get 'coding', to:'pages#coding'

  get 'about', to:'pages#about'

  get 'contact', to:'pages#contact'

  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	has_attached_file :image, styles: { large: "600x600", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def lifestyle
  end

  def videos
  end

  def coding
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:edit, :update, :show, :destroy]

	def index
		@posts = Post.all.order("updated_at DESC")
	end

	def new
		@post = Post.new
	end

	def create
    	@post = Post.new(post_params)

    	if @post.save
    		redirect_to @post
    	else
    		render 'new'
    	end
    end

	def edit
	end

	def update

		if @post.update(post_params)
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

  	private 
  	def post_params
  		params.require(:post).permit(:title, :date, :description, :image)
  	end

  	def set_post
  		@post = Post.find(params[:id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A female coder</title>
    <%= favicon_link_tag 'favicon2.ico' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    	<nav id= "nav">
          <div id= "page_nav">

           <%= image_tag ("Coco_logo2.jpg"), :class => "logo_pic" %>

           <%= render "shared/nav" %>
          
          </div>
      </nav> 

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
       
  </body>
</html>

app/views/pages/about.html.erb
<h1> About Me </h1>
<div class="aboutme">
	<ul>
		<div class="blockone">
			<li>
				<p> Hi, my name is Nicole Tingey, but I am better known by my nickname Coco. I am 18 years old, and ambitious to take on the world. That may sound cheesy, but learning is my passion and I have a strong desire to help people and make a difference in the world.</p>
			</li>
			<%= image_tag "IMG_0332.jpg", :class => "selfimage" %>
		</div>
		<li>
			<p> <strong class="strong">I am a female programmer.</strong> I take pride in this statement, and I love what I do. Learning Ruby on Rails this past year has been one of the coolest and most exciting, yet frusturating and crazy things I have ever challeneged myself to do. Many people told me that it wasn't a career for women, but I have come to find out that all of those people were wrong. Studying programming has brought so many amazing opportunities in to my life. I would HIGHLY reccomend this career for any female. </p>
		<%= image_tag "IMG_0898.jpg", :class => "selfimage" %>
		</li>
		<li>
			<p> During my free time I enjoy: 
				<li>Blogging</li>
				<li>Studying fashion</li>
				<li>Playing with my camera</li> 
				<li>Hanging out with the people I love</li>
				<li>Making videos</li>
				<li>Kick boxing</li>
				<li>Singing &#38; playing the ukulele</li>
				<li>CODING</li>
				<hr>
				<hr>
		</li>
		<%= image_tag "IMG_1094.jpg", :class => "selfimages" %>
		<%= image_tag "IMG_1322.jpg", :class => "selfimages" %>
		<%= image_tag "IMG_1703.jpg", :class => "selfimages" %>
		<%= image_tag "IMG_1747.jpg", :class => "selfimages" %>
		<%= image_tag "IMG_1654.jpg", :class => "selfimages" %>
	</ul>
</div>

app/views/pages/coding.html.erb
<h1>Coding</h1>

app/views/pages/contact.html.erb
<div class="contactpage">
	<h1>Email: nicole.tingey1@gmail.com </h1>
	<h1>Instagram: @cocotingsterr <a href="https://www.instagram.com/cocotingsterr"> My Instagram </a> </h1>
	<h1>Facebook: Coco Tingey <a href="https://www.facebook.com/coco.tingey"> My Facebook Page </a> </h1>
	<h1>Youtube: Coco Tingey <a href="https://www.youtube.com/channel/UCHlAB6CqCS7ZbBxifiq4V2w"> My Youtube Page </a> </h1>
	<h1> I check my email daily if you have any questions or are wanting to work togetger. Email is the best way to get in contact with me. </h1>
</div>
    <%= image_tag "resume.png", :class => "resumepic" %>

app/views/pages/home.html.erb
<div class="homepage">
	<%= image_tag("IMG_8187.jpg") %>
	<h1> Hi, my name is Coco. </h1>
</div>

app/views/pages/lifestyle.html.erb
<h1> Lifestyle </h1>


	

app/views/pages/videos.html.erb
<h1>Videos</h1>
<iframe width="400" height="320"
src="https://www.youtube.com/embed/7_nbZrI9DMU?controls=0">
</iframe>

<iframe width="400" height="320"
src="https://www.youtube.com/embed/WKCOs4wGfCU?controls=0">
</iframe>

<iframe width="400" height="320"
src="https://www.youtube.com/embed/mce6HhHQRR4?controls=0">
</iframe>

<iframe width="400" height="320"
src="https://www.youtube.com/embed/uBAOq8eUxmk?controls=0">
</iframe>

<iframe width="400" height="320"
src="https://www.youtube.com/embed/97Byeqv2IR4?controls=0">
</iframe>

<iframe width="400" height="320"
src="https://www.youtube.com/embed/vMVYbuFzNkw?controls=0">
</iframe>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="showpost">
	<% @posts.each do |post| %>
		<p><%= link_to post.title, post_path(post) %></p>
		<p><%= image_tag post.image.url(:medium) %> </p>
	<% end %>
</div>

<div class="newpost">
	<% if current_user && current_user.type == "Admin" %>
		<%= link_to 'New Post', new_post_path %>
	<% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="showpost"
	<p id="notice"> <%= notice %> </p>
	<div class="sppost">
		<%= image_tag @post.image.url(:large) %>
		
		<div class="titlepost">
		<p>
		  <%= @post.title %>
		</p>
		</div>
		<p>
		  <%= @post.date %>
		</p>

		<p>
		  <%= @post.description %>
		</p>

		<%= link_to 'Posts', posts_path %>

		<%= link_to 'Edit', edit_post_path %>
		<%= link_to "Delete", post_path(@post), :confirm => "Are you sure?", :method => :delete %>
	</div>

</div>

app/views/shared/_nav.html.erb
<%=link_to "Home", root_path, class: 'nav-item' %>
<%=link_to "Lifestyle", posts_path, class: 'nav-item' %>
<%=link_to "Videos", videos_path, class: 'nav-item' %>
<%=link_to "About", about_path, class: 'nav-item' %>
<%=link_to "Contact", contact_path, class: 'nav-item' %>
<% if user_signed_in? %>
	<%= link_to "Logout", destroy_user_session_path, :method => :delete, class: 'nav-item' %> 
<% else %>
	<%= link_to "Login", new_user_session_path, class: 'nav-item' %>  
<% end %>